name: Build EXE (EarLatencyApp)

on:
  workflow_dispatch:            # allow manual runs
  push:
    branches: [ "main" ]        # auto-run on main
    paths:
      - "ear_latency_app.py"
      - "requirements.txt"
      - ".github/workflows/build.yml"
      - "**/*.py"

permissions:
  contents: write               # needed for release publishing

jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --onefile --noconsole --name "EarLatencyApp" ear_latency_app.py
          dir dist

      - name: Upload artifact (.exe)
        uses: actions/upload-artifact@v4
        with:
          name: EarLatencyApp-windows
          path: dist/EarLatencyApp.exe
          if-no-files-found: error

  release:
    needs: build-windows
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: EarLatencyApp-windows
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**
